-- Add the `abandoned` value to IngestJobStatus for permanently-dead URLs
-- (HTTP 404 on landing pages — typically dead Heroku free-tier apps that
-- have been shut down). Distinct from `failed` so the dashboard's
-- actionable-failed count stays accurate and retry-failed naturally
-- skips them via the type rather than fragile regex matching on
-- lastError.
--
-- This migration ONLY adds the enum value. The backfill of existing
-- `failed` rows whose lastError indicates HTTP 404 lives in the
-- companion migration `20260524000001_backfill_abandoned_ingest_status`.
-- Postgres requires `ALTER TYPE ... ADD VALUE` to be committed before
-- the new value can be referenced in DML (error code 55P04 — "unsafe
-- use of new value"). Splitting into two migration files gives each
-- the Prisma-managed transaction boundary it needs.
ALTER TYPE "IngestJobStatus" ADD VALUE 'abandoned';
